"""AuthenticityProbe — direct genuine-vs-synthetic classification probe.

Unlike :class:`CentroidProbe` (which measures genuine-vs-synthetic *through*
per-sender centroid geometry — entangling identity with authenticity), this
probe asks a single, sender-agnostic question:

    Does the encoder's embedding space separate human-written emails from
    LLM-generated ("synthetic") ones — regardless of *who* the sender is?

This is the textbook *linear probe* diagnostic: take the trained encoder, put a
small classifier on top of its embeddings, and report how well it discriminates.
It isolates "is this machine-written?" (authenticity) from "is this Alice?"
(identity) — the latter being what the fraud / PrototypicalHead pipeline scores.

Label convention
----------------
Positive class (label 1) = **synthetic** (the thing we want to detect).
Negative class (label 0) = genuine. So AUROC/precision/recall all read as
"how well do we catch LLM-written email".

Sender-disjoint split
---------------------
Senders are partitioned into probe-train and probe-test buckets.  A sender's
real emails *and* its synthetic imitations both go to the same bucket (keyed on
``source_sender_id``), so the classifier is always evaluated on senders whose
style it never saw while fitting.  Without this, the probe could score high by
memorising per-sender quirks instead of genuine human-vs-LLM signal.

Two modes (both share the same split):
  - frozen   — encode once, fit an sklearn LogisticRegression on the embeddings.
               Measures what the *current* representation already encodes.
  - finetune — attach a linear head and train it with BCE (optionally with the
               encoder unfrozen).  Measures what the encoder *can be trained* to
               encode for this task.
"""

from __future__ import annotations

import logging
import random
from collections import defaultdict
from dataclasses import dataclass

import numpy as np
import torch
import torch.nn as nn

# Reuse the encoder-aware batch encoder (handles luar_episode_k=1 override).
from email_fraud.scoring.centroid_probe import _encode

logger = logging.getLogger(__name__)


@dataclass
class _Split:
    train_texts: list[str]
    train_labels: list[int]   # 1 = synthetic, 0 = genuine
    test_texts: list[str]
    test_labels: list[int]
    train_senders: list[str]  # source sender per example (diagnostic)
    test_senders: list[str]


class AuthenticityProbe:
    """Sender-disjoint genuine-vs-synthetic probe over encoder embeddings.

    Args:
        genuine_texts:            Real email bodies.
        genuine_senders:          Sender id per genuine email (the real sender).
        synthetic_texts:          LLM-generated email bodies.
        synthetic_source_senders: For each synthetic email, the real sender it
                                  was generated to imitate (``source_sender_id``
                                  in the synthetic Arrow dataset).
        test_frac:                Fraction of *senders* held out for the test
                                  bucket (default 0.3).
        max_per_class:            Optional cap on examples per class per bucket
                                  (applied after balancing). None = no cap.
        balance:                  Downsample the majority class within each
                                  bucket so genuine/synthetic counts match
                                  (default True — there are far more real emails).
        seed:                     RNG seed for reproducible sender split + sampling.
    """

    def __init__(
        self,
        genuine_texts: list[str],
        genuine_senders: list[str],
        synthetic_texts: list[str],
        synthetic_source_senders: list[str],
        test_frac: float = 0.3,
        max_per_class: int | None = None,
        balance: bool = True,
        seed: int = 0,
    ) -> None:
        if not synthetic_texts:
            raise ValueError(
                "AuthenticityProbe needs synthetic emails. Pass a non-empty "
                "synthetic_texts (generated by scripts/generate_synthetic_emails.py)."
            )
        self._seed = seed
        rng = random.Random(seed)

        gen_by_sender: dict[str, list[str]] = defaultdict(list)
        for t, s in zip(genuine_texts, genuine_senders):
            gen_by_sender[s].append(t)
        syn_by_sender: dict[str, list[str]] = defaultdict(list)
        for t, s in zip(synthetic_texts, synthetic_source_senders):
            syn_by_sender[s].append(t)

        # Only senders with BOTH real and synthetic emails can contribute both
        # classes to a bucket; restrict to the intersection so every bucket is
        # genuinely two-class.
        shared = sorted(set(gen_by_sender) & set(syn_by_sender))
        if not shared:
            raise ValueError(
                "No sender has both genuine and synthetic emails. Check that the "
                "synthetic dataset's source_sender_id values match the genuine "
                "split's sender_id values (same split?)."
            )
        rng.shuffle(shared)
        n_test = max(1, int(round(len(shared) * test_frac)))
        test_senders = set(shared[:n_test])
        train_senders = set(shared[n_test:])
        if not train_senders:
            raise ValueError(
                f"test_frac={test_frac} leaves no senders for training "
                f"(only {len(shared)} shared senders). Lower test_frac."
            )

        def _bucket(senders: set[str]) -> tuple[list[str], list[int], list[str]]:
            gen: list[tuple[str, str]] = []
            syn: list[tuple[str, str]] = []
            for sid in senders:
                gen.extend((t, sid) for t in gen_by_sender[sid])
                syn.extend((t, sid) for t in syn_by_sender[sid])
            rng.shuffle(gen)
            rng.shuffle(syn)
            if balance:
                n = min(len(gen), len(syn))
                gen, syn = gen[:n], syn[:n]
            if max_per_class is not None:
                gen, syn = gen[:max_per_class], syn[:max_per_class]
            texts = [t for t, _ in gen] + [t for t, _ in syn]
            labels = [0] * len(gen) + [1] * len(syn)
            src = [s for _, s in gen] + [s for _, s in syn]
            # Shuffle the combined list so batches aren't class-ordered.
            order = list(range(len(texts)))
            rng.shuffle(order)
            return ([texts[i] for i in order],
                    [labels[i] for i in order],
                    [src[i] for i in order])

        tr_texts, tr_labels, tr_src = _bucket(train_senders)
        te_texts, te_labels, te_src = _bucket(test_senders)

        self._split = _Split(
            train_texts=tr_texts, train_labels=tr_labels,
            test_texts=te_texts, test_labels=te_labels,
            train_senders=tr_src, test_senders=te_src,
        )

        logger.info(
            "AuthenticityProbe ready: %d train senders / %d test senders | "
            "train %d (%d syn) / test %d (%d syn)",
            len(train_senders), len(test_senders),
            len(tr_labels), sum(tr_labels),
            len(te_labels), sum(te_labels),
        )

    # ------------------------------------------------------------------
    # Mode 1: frozen linear probe (sklearn LogisticRegression)
    # ------------------------------------------------------------------

    @torch.no_grad()
    def evaluate_frozen(
        self,
        encoder,
        device: str,
        batch_size: int = 32,
        C: float = 1.0,
    ) -> dict[str, float]:
        """Freeze the encoder, fit LogisticRegression on embeddings, score test.

        Returns metrics prefixed ``probe_frozen/`` (see :func:`_classification_metrics`).
        """
        from sklearn.linear_model import LogisticRegression

        was_training = encoder.training
        encoder.eval()
        sp = self._split
        x_train = _encode(encoder, sp.train_texts, device, batch_size).numpy()
        x_test = _encode(encoder, sp.test_texts, device, batch_size).numpy()
        if was_training:
            encoder.train()

        y_train = np.array(sp.train_labels)
        y_test = np.array(sp.test_labels)

        clf = LogisticRegression(max_iter=1000, C=C, class_weight="balanced")
        clf.fit(x_train, y_train)
        y_score = clf.predict_proba(x_test)[:, 1]
        y_pred = (y_score >= 0.5).astype(int)

        out = _classification_metrics(y_test, y_score, y_pred, prefix="probe_frozen/")
        # Train-set fit quality is a useful "is the signal even there" sanity check.
        out["probe_frozen/train_accuracy"] = float(clf.score(x_train, y_train))
        return out

    # ------------------------------------------------------------------
    # Mode 2: fine-tuned linear head (BCE; encoder optionally unfrozen)
    # ------------------------------------------------------------------

    def evaluate_finetune(
        self,
        encoder,
        device: str,
        epochs: int = 5,
        lr: float = 1e-3,
        encoder_lr: float = 2e-5,
        batch_size: int = 32,
        unfreeze_encoder: bool = False,
    ) -> dict[str, float]:
        """Train a linear head (and optionally the encoder) with BCE, score test.

        With ``unfreeze_encoder=False`` only the head trains — a gradient-fit
        cousin of the frozen probe.  With ``unfreeze_encoder=True`` the encoder's
        trainable params (LoRA / projection, or the full backbone if it was built
        unfrozen) update too, answering "can this model *learn* the distinction".

        Returns metrics prefixed ``probe_finetune/``.
        """
        sp = self._split
        head = nn.Linear(encoder.embedding_dim, 1).to(device)

        # luar_episode pooling collapses K emails into one embedding; for a
        # per-email probe we force episode_k=1 for the duration (restored after).
        saved_k = None
        if getattr(encoder, "episode_k", None) is not None:
            saved_k = encoder.config.episode_k
            encoder.config.episode_k = 1

        param_groups = [{"params": head.parameters(), "lr": lr}]
        if unfreeze_encoder:
            enc_params = [p for p in encoder.parameters() if p.requires_grad]
            if enc_params:
                param_groups.append({"params": enc_params, "lr": encoder_lr})
            else:
                logger.warning(
                    "unfreeze_encoder=True but the encoder has no trainable "
                    "params (frozen backbone, no LoRA/projection). Training head only."
                )
        opt = torch.optim.AdamW(param_groups)
        loss_fn = nn.BCEWithLogitsLoss()

        x_texts = sp.train_texts
        y = torch.tensor(sp.train_labels, dtype=torch.float32, device=device)
        n = len(x_texts)
        rng = random.Random(self._seed)

        encoder.train() if unfreeze_encoder else encoder.eval()
        head.train()
        for epoch in range(epochs):
            order = list(range(n))
            rng.shuffle(order)
            total = 0.0
            for start in range(0, n, batch_size):
                idx = order[start : start + batch_size]
                batch_texts = [x_texts[i] for i in idx]
                batch_y = y[idx]
                tok = encoder.tokenize(batch_texts)
                tok = {k: v.to(device) for k, v in tok.items()}
                grad_ctx = torch.enable_grad() if unfreeze_encoder else torch.no_grad()
                with grad_ctx:
                    embs = encoder.encode(**tok)
                if not unfreeze_encoder:
                    embs = embs.detach()
                logits = head(embs).squeeze(-1)
                loss = loss_fn(logits, batch_y)
                opt.zero_grad()
                loss.backward()
                opt.step()
                total += loss.item() * len(idx)
            logger.info("finetune epoch %d/%d  loss=%.4f", epoch + 1, epochs, total / n)

        # Evaluate on held-out senders.
        encoder.eval()
        head.eval()
        scores: list[float] = []
        with torch.no_grad():
            for start in range(0, len(sp.test_texts), batch_size):
                batch_texts = sp.test_texts[start : start + batch_size]
                tok = encoder.tokenize(batch_texts)
                tok = {k: v.to(device) for k, v in tok.items()}
                embs = encoder.encode(**tok)
                logits = head(embs).squeeze(-1)
                scores.extend(torch.sigmoid(logits).cpu().tolist())

        if saved_k is not None:
            encoder.config.episode_k = saved_k

        y_test = np.array(sp.test_labels)
        y_score = np.array(scores)
        y_pred = (y_score >= 0.5).astype(int)
        return _classification_metrics(y_test, y_score, y_pred, prefix="probe_finetune/")

    # ------------------------------------------------------------------
    # Introspection
    # ------------------------------------------------------------------

    @property
    def counts(self) -> dict[str, int]:
        sp = self._split
        return {
            "train_total": len(sp.train_labels),
            "train_synthetic": sum(sp.train_labels),
            "test_total": len(sp.test_labels),
            "test_synthetic": sum(sp.test_labels),
        }


def _classification_metrics(
    y_true: np.ndarray,
    y_score: np.ndarray,
    y_pred: np.ndarray,
    prefix: str = "",
) -> dict[str, float]:
    """Binary classification metric bundle (positive class = synthetic).

    Reports accuracy, balanced accuracy, ROC-AUC, PR-AUC (average precision),
    precision/recall/F1, the confusion-matrix cells, and a majority-class
    baseline so the headline accuracy can be read against chance.
    """
    from sklearn.metrics import (
        accuracy_score,
        average_precision_score,
        balanced_accuracy_score,
        f1_score,
        precision_score,
        recall_score,
        roc_auc_score,
    )

    out: dict[str, float] = {}
    n = len(y_true)
    n_pos = int(y_true.sum())          # synthetic
    n_neg = n - n_pos                  # genuine

    out[f"{prefix}accuracy"] = float(accuracy_score(y_true, y_pred))
    out[f"{prefix}balanced_accuracy"] = float(balanced_accuracy_score(y_true, y_pred))
    # AUROC/AP need both classes present.
    if n_pos and n_neg:
        out[f"{prefix}roc_auc"] = float(roc_auc_score(y_true, y_score))
        out[f"{prefix}pr_auc"] = float(average_precision_score(y_true, y_score))
    out[f"{prefix}precision"] = float(precision_score(y_true, y_pred, zero_division=0))
    out[f"{prefix}recall"] = float(recall_score(y_true, y_pred, zero_division=0))
    out[f"{prefix}f1"] = float(f1_score(y_true, y_pred, zero_division=0))

    tp = int(((y_pred == 1) & (y_true == 1)).sum())
    fp = int(((y_pred == 1) & (y_true == 0)).sum())
    tn = int(((y_pred == 0) & (y_true == 0)).sum())
    fn = int(((y_pred == 0) & (y_true == 1)).sum())
    out[f"{prefix}tp"] = float(tp)
    out[f"{prefix}fp"] = float(fp)
    out[f"{prefix}tn"] = float(tn)
    out[f"{prefix}fn"] = float(fn)

    out[f"{prefix}n_test"] = float(n)
    out[f"{prefix}n_synthetic"] = float(n_pos)
    out[f"{prefix}n_genuine"] = float(n_neg)
    # Always-predict-majority accuracy: the floor any real probe must beat.
    out[f"{prefix}majority_baseline"] = float(max(n_pos, n_neg) / n) if n else 0.0
    return out
